package dev.team.githubtrendanalysis.models;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class LicenseRepoCount {
    private String license;
    private long repoCount;

    // Getters and setters are generated by Lombok
}
